[package]
name = "ckb-sdk"
version = "2.5.0"
authors = ["Linfeng Qian <thewawar@gmail.com>", "Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "Rust SDK for CKB"
homepage = "https://github.com/nervosnetwork/ckb-sdk-rust"
repository = "https://github.com/nervosnetwork/ckb-sdk-rust"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.30"
anyhow = "1.0.63"
bech32 = "0.8.1"
derive-getters = "0.2.1"
log = "0.4.6"
reqwest = { version = "0.11", features = ["json", "blocking"] }
secp256k1 = { version = "0.24", features = ["recovery"] }
tokio-util = { version = "0.7.7", features = ["codec"] }
tokio = { version = "1" }
bytes = "1"
futures = "0.3"
jsonrpc-core = "18"
parking_lot = "0.12"
lru = "0.7.1"
dashmap = "5.4"
dyn-clone = "1.0"

ckb-types = "0.111.0-rc6"
ckb-dao-utils =  "0.111.0-rc6"
ckb-traits =  "0.111.0-rc6"
ckb-jsonrpc-types  =  "0.111.0-rc6"
ckb-hash =  "0.111.0-rc6"
ckb-resource =  "0.111.0-rc6"
ckb-crypto = { version = "=0.111.0-rc6", features = ["secp"] }
ckb-script = "0.111.0-rc6"
bitflags = "1.3.2"
sha3 = "0.10.1"
enum-repr-derive = "0.2.0"

# for feature test
rand = { version = "0.7.3", optional = true }
ckb-mock-tx-types = { git = "https://github.com/nervosnetwork/ckb-standalone-debugger", branch = "develop"}
ckb-chain-spec = "0.111.0-rc6"

sparse-merkle-tree = "0.6.1"
lazy_static = "1.3.0"

[features]
default = []
test = []

[dev-dependencies]
clap = { version = "4.1.8", features = ["derive"] }
httpmock = "0.6"
async-global-executor = "2.3.1"
hex = "0.4"
